### ISSUE TITLE
Problems with datasets

### ISSUE THREAD

**Issue by kyre-99** [aj1365/PolSARFormer#1]
Hello, I am very happy to see your research results, I am a graduate student, also working on polarized SAR Landcover classification problems。But I haven't been able to find these open source dataset to downloadcan you share the dataset you used in this article: Flevoland dataset, San Francisco dataset. If you can, thanks for sending me 1421223705@qq.com email, thanks.

**Comment by jkjam7** [comment]
I also want the two datasets Flevoland and San Francisco used in the code, if you can share them, please send them to the email jkjam7@163.com, thank you very much.

**Comment by aj1365** [comment]
@kyre-99 and @jkjam7, you can check this address: 
https://github.com/liuxuvip/PolSF

**Comment by swalpa** [comment]
done
