### ISSUE TITLE
Problems with the code

### ISSUE THREAD

**Issue by AugustWXJ** [aj1365/PolSARFormer#2]
Thanks for your very nice code. 
I met a problem with your code:
At the end of the PolSARFormer model, the code below just takes the x as the input, thus the output nn of the PolSARFormer is just the results of the output_block, and the attention operation is unused.
'nn = output_block(x, num_classes=num_classes, drop_rate=dropout, classifier_activation=classifier_activation)'

So I wonder if there is a mistake, and if the 'x' in the code should be takeplaced by other variable.

**Comment by aj1365** [comment]
Yeah, it was a mistake. It supposed to be nn!!
I corrected it.
Thanks.

**Comment by AugustWXJ** [comment]
Thanks for your reply!
