### ISSUE TITLE
Problems with the test_ratio

### ISSUE THREAD

**Issue by TuffyY** [aj1365/PolSARFormer#3]
Thanks for your very nice code.
I have a doubt, is setting the test_ratio to 0.9 too large?

**Comment by aj1365** [comment]
No, the lower number of training data would illustrate the efficiency of the method while having a low number of training data. Most DCNNs and ViTs require a significant number of reference (ground truth) data.

**Comment by TuffyY** [comment]
Thanks for your reply!
